# Generated by Django 2.2.1 on 2019-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_send_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
